// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP7uCR8E9XC4Tx7s7B4l7piPxKDLK2rYY',
    appId: '1:880975820992:android:d21460c2863f39826e9525',
    messagingSenderId: '880975820992',
    projectId: 'gong-nol',
    databaseURL: 'https://gong-nol-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gong-nol.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBN02-jNs84EQN3YuFMpHaQ1An4ONXjkc',
    appId: '1:880975820992:web:093f53880e789c496e9525',
    messagingSenderId: '880975820992',
    projectId: 'gong-nol',
    authDomain: 'gong-nol.firebaseapp.com',
    databaseURL: 'https://gong-nol-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gong-nol.firebasestorage.app',
    measurementId: 'G-CFQ0NLKL9D',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBN02-jNs84EQN3YuFMpHaQ1An4ONXjkc',
    appId: '1:880975820992:web:9f41e00243fac7bd6e9525',
    messagingSenderId: '880975820992',
    projectId: 'gong-nol',
    authDomain: 'gong-nol.firebaseapp.com',
    databaseURL: 'https://gong-nol-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gong-nol.firebasestorage.app',
    measurementId: 'G-YSC77SNW4E',
  );

}