// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaZHFc_pHap2ewQVpC_KbSOg-U8y1dTIg',
    appId: '1:262630422734:web:88143442a73f527109b89f',
    messagingSenderId: '262630422734',
    projectId: 'seoul-game',
    authDomain: 'seoul-game.firebaseapp.com',
    storageBucket: 'seoul-game.firebasestorage.app',
    measurementId: 'G-9Z2GNB8VM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsn2HKUBqBqxhXh-icRt-r-MxgQcQbHwQ',
    appId: '1:262630422734:android:e294bb88c4207c8409b89f',
    messagingSenderId: '262630422734',
    projectId: 'seoul-game',
    storageBucket: 'seoul-game.firebasestorage.app',
  );
}
